apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-minio-startup"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  stsonly.json: {{ include "datalab.minio.stspolicy" . | toJson }}
