apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secrets
  #labels:
  #  app.kubernetes.io/managed-by: {{ .Release.Service }}
  #  app.kubernetes.io/instance: {{ .Release.Name }}
  #  helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
stringData:
  psql-password: gitlab-password
  email-password: "passowrd"
  connection: |
    provider: AWS
    # Specify the region
    region: eu-west-1
    # Specify access/secret keys
    aws_access_key_id: {{ .Values.dminio.auth.rootUser }} 
    aws_secret_access_key: {{ .Values.dminio.auth.rootPassword }}
    # The below settings are for S3 compatible endpoints
    #   See https://docs.gitlab.com/ee/administration/job_artifacts.html#s3-compatible-connection-settings
    aws_signature_version: 4
    host: minio.{{ .Values.domainName }}
    endpoint: "https://minio.{{ .Values.domainName }}:9000"
    path_style: true
  redis-password: "redis-password"
  s3cmd-config: | 
    access_key: {{ .Values.dminio.auth.rootUser }} 
    secret_key: {{ .Values.dminio.auth.rootPassword }}
    bucket_location: eu-west-1
    multipart_chunk_size_mb: 128
  minio-credentials: |
    access_key: {{ .Values.dminio.auth.rootUser }} 
    secret_key: {{ .Values.dminio.auth.rootPassword }}
  registry-storage : |
    s3:
      v4auth: true
      regionendpoint: "https://minio.{{ .Values.domainName }}"
      pathstyle: true
      region: eu-west-1
      bucket: gitlab-registry-storage
      accesskey: {{ .Values.dminio.auth.rootUser }} 
      secretkey: {{ .Values.dminio.auth.rootPassword }}
  ssoProvider: |
    name: "openid_connect"
    label: "Datalab Keycloak"
    args: 
      name: "openid_connect"
      scope: ["openid","profile","email"]
      response_type: "code"
      issuer: "https://keycloak.{{ .Values.domainName }}/auth/realms/datalab-demo"
      discovery: false
      client_auth_method: "query"
      uid_field: "preferred_username"
      client_options:
        identifier: "gitlab-client"
        secret: {{ .Values.gitlab.clientsecret }}
        redirect_uri: "https://gitlab.{{ .Values.domainName }}/users/auth/openid_connect/callback"
        authorization_endpoint: "https://keycloak.{{ .Values.domainName }}/auth/realms/datalab-demo/protocol/openid-connect/auth"
        token_endpoint: "https://keycloak.{{ .Values.domainName }}/auth/realms/datalab-demo/protocol/openid-connect/token"
        userinfo_endpoint: "https://keycloak.{{ .Values.domainName }}/auth/realms/datalab-demo/protocol/openid-connect/userinfo"
        jwks_uri: "https://keycloak.{{ .Values.domainName }}/auth/realms/datalab-demo/protocol/openid-connect/certs"
        end_session_endpoint: "https://keycloak.{{ .Values.domainName }}/auth/realms/datalab-demo/protocol/openid-connect/logout"
