apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-realm-secret"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  realm.json: {{ include "keycloak.realm.config" . | b64enc  }}