apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-superset-client-secret"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
stringData:
  client_secret.json: |
    {
    "web": {
        "issuer": "https://{{ .Values.superset.configSSO }}/auth/realms/datalab-demo",
        "auth_uri": "https://{{ .Values.superset.configSSO }}/auth/realms/datalab-demo/protocol/openid-connect/auth",
        "client_id": "apache-superset",
        "client_secret": "{{ .Values.superset.clientsecret }}",
        "redirect_uris": [
          {{- with index .Values.superset.ingress.hosts 0 -}}
            "https://{{ . }}/*"
          {{- end -}}
        ],
        "userinfo_uri": "https://{{ .Values.superset.configSSO }}/auth/realms/datalab-demo/protocol/openid-connect/userinfo",
        "token_uri": "https://{{ .Values.superset.configSSO }}/auth/realms/datalab-demo/protocol/openid-connect/token",
        "token_introspection_uri": "https://{{ .Values.superset.configSSO }}/auth/realms/datalab-demo/protocol/openid-connect/token/introspect"
    }
    }

