apiVersion: v2
name: datalab
description: A Cloud Agnostic Data Lab Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.10.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

# The core service charts that will be installed
dependencies:
  - name: minio
    version: 10.1.12
    repository: https://charts.bitnami.com/bitnami
    alias: dminio
  - name: keycloak
    version: 15.1.0
    repository: https://codecentric.github.io/helm-charts
  - name: onyxia
    version: 2.0.0
    repository: https://inseefrlab.github.io/helm-charts
  - name: vault
    version: 0.18.0
    repository: https://helm.releases.hashicorp.com
  - name: prometheus
    version: 15.0.1
    repository: https://prometheus-community.github.io/helm-charts
    alias: dprometheus
  - name: grafana
    version: 6.17.10
    repository: https://grafana.github.io/helm-charts
  - name: postgresql
    version: 10.13.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    alias: dpostgresql
  - name: ckan
    version: 1.0.1
    repository: https://keitaro-charts.storage.googleapis.com
    condition: ckan.enabled
  - name: superset
    version: 0.5.9
    repository: https://apache.github.io/superset
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.1.0
    alias: dredis
  - name: gitlab
    version: 5.7.0
    repository: https://charts.gitlab.io
  - name: kubernetes-dashboard
    version: 2.5.0
    repository: https://kubernetes.github.io/dashboard/